# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0afc81409e6b6cfbe46c1fddba2b84297b067aaa03f3163198f16393eb16540acd6cbb9640c13875622cd9a7a0e02f68e32b05abff52c5b10546641bca1c20c3

test:
  secret_key_base: 5562a22a09c864a870b90c20285eb827d54febcde2266dfa6f4ddb73b09321bf42c28e476b08d1f4a507f26cc6011ba46cc1874921f04c3ddd28e0178a14f1ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
