# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d16662abed7d2b79077a721544790f84c707ae4d9e677f10763dfe796ee494915d58db21f868370bfe53f889f975ef440c38f3d6573ad22f5a3a0b33eb78361b

test:
  secret_key_base: efc9b4c20490642a8226425a375541277b3b432ea805d2b6f7a49b7ea557509605afafb0f0235721197c7fce0426e4bc204e924198675a96eba68bc84ad461aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
