# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a06edb7806d2dccd8fbeb9e539dfc9c8b354bac544bc183729eec2d4771b55d6b1a28dd2fc38bd5a4affe367b523a51064a31f14c91f431a11342b08e0df448

test:
  secret_key_base: e690ad29e06f2c53b4971868bf7e4d5c5d50a2ba5e41bdca9a023b1444474b1938ba914626bd93c1d1b0409cd0f180a7c16a8ee7a13a2f638963f165d55b1ee3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
